
- name: remove docker repository
  file:
    path: /etc/yum.repos.d/docer-ce.repo
    state: absent

- name: install epel for Amazon Linux2
  shell: "amazon-linux-extras install epel -y"
  changed_when: False

- name: yum install repos
  yum: 
    name:
      - https://repo.ius.io/ius-release-el7.rpm 
    state: latest

- name: yum update all
  yum: 
    name: '*'
    state: latest

- name: yum install basic package
  yum: 
    name:
      - kernel-headers
      - kernel-devel
      - gcc
      - bzip2
    state: latest
