- name: add docker group
  group:
    name: keycloak
    state: present
  tags: keycloak

- name: create data/conf dir.
  file:
    path: "/home/keycloak/{{ item }}"
    state: directory
    owner: keycloak
    group: keycloak
    mode: 0755
  with_items:
    - mysql/data
    - nginx/conf
    - nginx/certs
    - nginx/log
  tags: keycloak

- name: copy docker-compose.yml
  template:
    src: docker-compose.j2
    dest: /home/keycloak/docker-compose.yml
    owner: keycloak
    group: keycloak
    mode: 0644
  tags: keycloak

- name: spin up docker-compose
  shell: docker-compose up -d
  args:
    chdir: /home/keycloak
  become: yes
  tags: keycloak
