- name: show server domain
  debug:
    msg: "{{ server_domain }}"
  tags: keycloak

- name: add keycloak group
  group:
    name: keycloak
    state: present
  tags: keycloak

- name: copy docker-compose.yml
  template:
    src: docker-compose.j2
    dest: /home/keycloak/docker-compose.yml
    owner: keycloak
    group: keycloak
    mode: 0644
  tags: keycloak

- name: spin up docker-compose
  shell: docker-compose up -d
  args:
    chdir: /home/keycloak
  become: yes
  tags: keycloak
