- name: set hostname
  hostname:
    name: "{{ ldap_server_domain }}"
  tags: ldap

- name: yum install 389ds/ldap
  yum: 
    name: 
      - 389-ds-base
      - 389-admin
      - openldap-clients
    state: latest
  tags: ldap

- name: 389ds setup script
  template:
    src: install.j2
    dest: /tmp/install.inf
    owner: root
    group: root
    mode: 0644
  tags: ldap

# - name: set up 389ds
#   shell: /root/setup-ds.sh
#   become: yes
#   ignore_errors: yes
#   tags: ldap
