- name: show server domain
  debug:
    msg: "{{ server_domain }}"
  tags: ldap

- name: copy docker-compose.yml
  template:
    src: docker-compose.j2
    dest: /home/ldap/docker-compose.yml
    owner: root
    group: root
    mode: 0644
  tags: ldap

- name: spin up docker-compose
  shell: docker-compose up -d
  args:
    chdir: /home/ldap
  become: yes
  tags: ldap
