- name: show server domain
  debug:
    msg: "{{ server_domain }}"
  tags: httpd

- name: create data/conf dir.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - /etc/httpd/conf/
    - /var/log/httpd/
    - /var/www/html/
    - /var/www/html/closed/
    - /var/www/html/open/
  tags: web

- name: copy httpd.conf
  copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - {file: httpd.conf, dest: /etc/httpd/conf/httpd.conf}
    - {file: index.html, dest: /var/www/html/index.html}
    - {file: index_open.html, dest: /var/www/html/open/index.html}
    - {file: index_closed.html, dest: /var/www/html/closed/index.html}
    - {file: loggedout.html, dest: /var/www/html/closed/loggedout.html}
  tags: web

- name: copy auth_openidc.conf
  template:
    src: auth_openidc.j2
    dest: /etc/httpd/conf/auth_openidc.conf
    mode: 0644
  tags: web

- name: copy docker-compose.yml
  template:
    src: docker-compose.j2
    dest: /home/web/docker-compose.yml
    owner: web
    mode: 0644
  tags: web

- name: check docker-compose.yml dir.
  stat: {
    path: "/home/web/docker-compose.yml"
  }
  register: fm
  tags: web

- name: spin up docker-compose
  shell: docker-compose up -d
  args:
    chdir: /home/web
  become: yes
  when:
    - fm.stat.exists is defined
    - fm.stat.exists
  tags: web
