- name: set OS name
  shell: uname -s
  register: os_name
  tags: docker

- name: show OS name
  debug:
    msg: "{{ os_name }}"
  tags: docker

- name: set CPU name
  shell: uname -m
  register: cpu_name
  tags: docker

- name: show CPU name
  debug:
    msg: "{{ cpu_name }}"
  tags: docker

- name: check docker-compose exists
  stat: {
    path: "/usr/local/bin/docker-compose"
  }
  register: fm
  tags: docker

- name: download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_ver }}/docker-compose-{{ os_name.stdout }}-{{ cpu_name.stdout }}"
    dest: /usr/local/bin/docker-compose
    force: yes
    mode: 0755
  when:
    - os_name.stdout is defined
    - cpu_name.stdout is defined
    - fm.stat.exists is defined
    - not fm.stat.exists
  tags: docker

- name: check docker-compose exists again
  stat: {
    path: "/usr/local/bin/docker-compose"
  }
  register: fm
  tags: docker

- name: create docker-compose symbolic link
  file:
    src: "/usr/local/bin/docker-compose"
    dest: "/usr/bin/docker-compose"
    state: link
    force: yes
  when:
    - fm.stat.exists is defined
    - fm.stat.exists
  tags: docker
