- hosts: keycloak
  become: yes
  vars:
    server_domain: "{{ kc_server_domain }}"
    server_email: "{{ kc_server_email }}"
    server_port: "{{ kc_server_port }}"
  roles:
    - common
    - docker
    - keycloak
