- hosts: ldap
  become: yes
  vars:
    server_domain: "{{ ldap_server_domain }}"
    server_email: "{{ ldap_server_email }}"
    server_port: "{{ ldap_admin_server_port }}"
  roles:
    - common
    - docker
    - ldap
