- hosts: web
  become: yes
  vars:
    server_domain: "{{ web_server_domain }}"
    server_email: "{{ web_server_email }}"
    server_port: "{{ web_server_port }}"
  roles:
    - common
    - docker
    - web
